services:
  bff-frontoffice-gia:
    container_name: bff-frontoffice-gia
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0:3080"
    environment:
      - STAGE=${STAGE:-PROD}
      - APP_NAME=${APP_NAME:-bff-frontoffice-gia}
      - APP_PORT=3080
      - APP_DEFAULT_LANG=${APP_DEFAULT_LANG:-es}
      - REDIS_HOST=${REDIS_HOST:-redis-global-gia}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - BFF_CACHE_ENABLED=${BFF_CACHE_ENABLED:-true}
      - BFF_CACHE_DEFAULT_TTL=${BFF_CACHE_DEFAULT_TTL:-300}
      - MS_AUTH_URL=${MS_AUTH_URL:-http://ms-auth-gia:3020}
      - MS_AGENTS_URL=${MS_AGENTS_URL:-http://ms-agents-gia:3040}
    networks:
      - coolify

networks:
  coolify:
    external: true
