services:
  bff-frontoffice-gia:
    build:
      context: .
      target: development
    command: npx --yes tsx watch index.ts
    ports:
      - "0:3100"
    environment:
      - APP_PORT=3100
      - TENANT_ID=${TENANT_ID}
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./index.ts:/app/index.ts
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml

networks:
  default:
    name: gia-network
    external: true
